### ISSUE TITLE
Executable is detected as virus on Windows10 by Windows Security

### ISSUE THREAD

**Issue by AdrienLeblanc** [ForsakenNGS/LogTrackerApp#1]
Hello,

I tried using the app, so far when I managed to make it running on my PC it worked like a charm. Thanks !
But Windows spots it as a virus and makes it way harder to execute the app.

Is there any way you can fix it ?

![image](https://user-images.githubusercontent.com/19342228/228612185-01851d64-e3e8-4e30-98f6-c511cae7b08f.png)

**Comment by ForsakenNGS** [comment]
I researched this and it seems possible to submit false positives to microsoft for review. Can you tell me which version of windows defender detects this as malware? (Win11/Win10/Win8 or Win7 and lower)

**Comment by AdrienLeblanc** [comment]
I am using Windows 10

**Comment by ForsakenNGS** [comment]
A friend of mine checked both versions 1.1.6 and 1.1.8 and did not have an issue with either of those. (Also Windows 10 with the current malware definitions)

I submitted the latest version to Microsoft for review. I hope it's possible to solve the issue that way. Strangely when uploaded the reported malware changed to "Program:Win32/Wacapew.C!ml" (Another machine learning profile)

Not sure what is going on there...

**Comment by ForsakenNGS** [comment]
Feedback from Microsoft regarding this issue:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
>
>     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>     3. Run "MpCmdRun.exe -SignatureUpdate"
>
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

**Comment by AdrienLeblanc** [comment]
Cool, thanks !
